---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: pfsense_modules
outputs:
 - name: certificates
params:
  SUBJECT:
  EXPIRE_DAYS:
  PORT:


run:
  path: pfsense_modules/ci/scripts/check_cert_expiration.sh
