---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: pfsense_modules
 - name: variable
outputs:
 - name: certificates
params:
  SUBJECT:
  PFSENSE_FQDN: 
  PFSENSE_USERNAME: 
  PFSENSE_PASSWORD: 


run:
  path: pfsense_modules/ci/scripts/request_cert.sh
