---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: pfsense-modules
outputs:
 - name: certificates
params:
  SUBJECT:
  CERT_ID:
  CA_ID_R10:
  CA_ID_R11:
  CA_ID_R3:
  STORED_CERT:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  CREDHUB_CA_CERT:  
  PFSENSE_FQDN: 
  PFSENSE_USERNAME: 
  PFSENSE_PASSWORD: 


run:
  path: pfsense-modules/ci/scripts/request_cert.sh
